#!/bin/python

for i in range(1, 11):
    print("Hola Mundo",i)

for i in range(1, 11, 2):
    print("Hola Mundo",i)

lista = ['david', 'carlos', 'ana', 'luis']
print(lista)

for i in lista:
    print("Hola Mundo",i)
